// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

// MACTYPE
user_pref("gfx.direct2d.disabled",   "true");
user_pref("gfx.font_loader.delay",   "-1");
user_pref("gfx.font_rendering.cleartype.always_use_for_content;true",    "true");
user_pref("gfx.font_rendering.cleartype_params.cleartype_level",     "100");
user_pref("gfx.font_rendering.cleartype_params.enhanced_contrast",   "100");
user_pref("gfx.font_rendering.cleartype_params.gamma",   "1400");
user_pref("gfx.font_rendering.cleartype_params.pixel_structure",     "1");
user_pref("gfx.font_rendering.cleartype_params.rendering_mode",  "5");
user_pref("gfx.font_rendering.fallback.always_use_cmaps",    "true");
user_pref("gfx.use_text_smoothing_setting",  "true");
user_pref("font.name.monospace.x-western","Source Code Pro");
user_pref("font.name.sans-serif.x-western","Source Sans Pro");
user_pref("font.name.serif.x-western", "Source Serif Pro");
